services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geoscraper_nuxt_app
    restart: unless-stopped
    ports:
      - "20001:3000"
    env_file:
      - .env
    networks:
      - shared_app_net

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: geoscraper_python_worker
    restart: unless-stopped
    volumes:
      - ~/share/data:/data
    env_file:
      - .env
    networks:
      - shared_app_net

networks:
  shared_app_net:
    external: true
    name: shared-db-network