services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geoscraper_nuxt_app
    restart: unless-stopped
    ports:
      - "20001:3000"
    volumes:
      - "${STORAGE_HOST_PATH:-./geoscraper-tiles-data}:/data/geoscraper-tiles"
    env_file:
      - .env
    networks:
      - shared_app_net

networks:
  shared_app_net:
    external: true
    name: shared-db-network