packages: []

catalogs:
  backend:
    '@types/pg': ^8.15.4
    bullmq: ^5.56.4
    drizzle-kit: ^0.31.4
    drizzle-orm: ^0.44.3
    pg: ^8.16.3
    redis: ^5.6.0
    undici: ^7.11.0
  build:
    '@nuxt/devtools': ^2.6.2
    '@nuxt/eslint': ^1.5.2
    '@nuxt/kit': ^3.17.6
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.1
    '@unocss/eslint-config': ^66.3.3
    '@unocss/nuxt': ^66.3.3
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.5.0
    nuxt: ^3.17.6
    unocss: ^66.3.3
    unplugin: ^2.3.5
    vite: ^7.0.5
  dev:
    '@antfu/eslint-config': ^4.17.0
    eslint: ^9.31.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    vue-tsc: ^3.0.1
  frontend:
    '@vueuse/core': ^13.5.0
    maplibre-gl: ^5.6.1
    pinia: ^3.0.3
    vue: ^3.5.17
  icons:
    '@iconify-json/carbon': ^1.2.10
    '@iconify-json/twemoji': ^1.2.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
